[package]
name = "mining_manager"
version = "0.1.0"
description = "Kaspa mining manager"
edition = "2021"
authors = ["Kaspa developers"]
include = [
    "src/**/*.rs",
]

[dependencies]
consensus-core = { path = "../consensus/core" }
